/*
CSC 134
M2HW1 - Gold
Austin Cowart
03/02/2026
*/

#include <iostream>
#include <iomanip>
using namespace std;

void question_one(){
    // Question 1
    cout << "Question 1" << endl;
    
    // The Name of the User
    string username;
    cout << "Hello! " << "What's your name? " << endl;
    cin >> username;
    cout << "Hello, " << username << endl;

    // Determine Inital Account Balance
    int starting_balance;

}

int main(){

    return 0;
}